import os

# This file is the entry point for the FastAPI application.
# It sets up the API, configures cross-origin access for the frontend,
# includes all route modules, and defines a basic health check endpoint.
# This file is important because it is the central place where the backend
# application is assembled and made available to clients.
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from sqlalchemy.exc import IntegrityError
# CORS middleware allows the backend to accept requests from a different origin,
# such as the local frontend dev server running on localhost:5173.
# This is important when the frontend and backend are served separately during
# development, because browsers enforce a same-origin policy by default.
from fastapi.middleware.cors import CORSMiddleware

# Import all router modules that define API endpoints for specific features.
# Each router groups related endpoints such as branches, ATMs, authentication,
# and service calls, making the application easier to organize and maintain.
from app.routers import atms, branches, auth, service_calls
from app.config import settings


FRONTEND_ORIGIN = settings.frontend_origin
ALLOWED_ORIGINS = [
    FRONTEND_ORIGIN,
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# Create the FastAPI application instance.
# The metadata here helps with API documentation generated by FastAPI,
# which is valuable for developers and testers using the /docs UI.
app = FastAPI(
    title="ATM machine tracker",
    description="ATM Mangement API for CashCow Project",
    version="0.2.0",
)

# Configure CORS so the frontend can communicate with this API.
# Without this, browser-based clients from a different origin would be blocked
# from making requests, which would break the frontend-backend connection.
app.add_middleware(
    CORSMiddleware,
    # Allow the frontend running on the Vite dev server to call the API.
    # This is the origin that the browser sees when the frontend is served locally.
    allow_origins=ALLOWED_ORIGINS,
    # Allow cookies and credentials to be included in cross-origin requests.
    # This is especially important for JWT-based authentication flows.
    allow_credentials=True,
    # Allow all standard HTTP methods so the frontend can perform CRUD-style actions.
    allow_methods=["*"],
    # Allow all headers, including Authorization headers used by JWT tokens.
    allow_headers=["*"],
)

# Include each router module in the application.
# Each router contains endpoint definitions for a specific domain, which keeps the
# code modular and easier to maintain as the project grows.
app.include_router(branches.router)
app.include_router(atms.router)
app.include_router(auth.router)
app.include_router(service_calls.router)

# Define a simple health check endpoint.
# This is an important operational endpoint because it allows monitoring tools,
# deployment checks, and developers to confirm the API is running correctly.
@app.get("/health", tags=["health"])
async def health_check() -> dict[str, str]:
    # Return a simple status payload so external systems can verify the app is live.
    return {"status": "ok"}

@app.get("/version", tags=["health"])
async def version() -> dict[str, str]:
    return {"version": app.version}

@app.exception_handler(IntegrityError)
async def integrity_error_handler(request: Request, exc: IntegrityError) -> JSONResponse:
    # Handle database integrity errors gracefully by returning a structured JSON response.
    # This prevents the application from crashing and provides useful feedback to clients.
    return JSONResponse(
        status_code=409,
        content={"detail": "Database integrity error: likely a duplicate or constraint violation."},
    )

@app.exception_handler(Exception)
async def generic_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    return JSONResponse(
        status_code=500,
        content={"detail": "An unexpected error has occurred. Please try again later."}
    )